services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: abidhasan83/agrolink-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://abidhasan7116:YpLEaZIAY0AmR4j0@cluster0.lx8cqwh.mongodb.net/AGROLINK?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3000
      - JWT_SECRET=mysecret
      - CLOUDINARY_CLOUD_NAME=dcvkttktl
      - CLOUDINARY_API_KEY=931199518597945
      - CLOUDINARY_API_SECRET=efPviLx3FH1b_NsMxPamZKS3_jo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    image: abidhasan83/agrolink-mobile:latest
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped




      # services:
#   backend:
#     build: ./backend
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb+srv://abidhasan7116:YpLEaZIAY0AmR4j0@cluster0.lx8cqwh.mongodb.net/AGROLINK?retryWrites=true&w=majority&appName=Cluster0
#       - PORT=3000
#       - JWT_SECRET=mysecret
#       - CLOUDINARY_CLOUD_NAME=dcvkttktl
#       - CLOUDINARY_API_KEY=931199518597945
#       - CLOUDINARY_API_SECRET=efPviLx3FH1b_NsMxPamZKS3_jo

#   mobile:
#     build: ./mobile
#     ports:
#       - "8081:8081"
#     environment:
#       - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
#       - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
#     depends_on:
#       - backend

